version: '3.3'

services:
  postgres:
    image: postgres:latest
    container_name: CURSO_NODE_POSTGRES
    environment:
      - POSTGRES_DB=my_store
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin123
    ports:
      - 5432:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  pgadmin: 
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@root.com  
      - PGADMIN_DEFAULT_PASSWORD=admin123
    ports:
      - 5050:80